### ISSUE TITLE
Embedded comments on other sites are being styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/Discourse-Dark#18]
I'm thinking it might be good to exclude the embedded commenting url from styling since it messes up the look of the site it's being used on. It took me a bit to realize nothing was wrong here and they were using Discourse for the comments too.

* **Browser**: chrome
* **Operating System**: win10
* **Url**: https://www.home-assistant.io/blog (any post on this blog, they all use their discourse site for commenting)
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/50558915-d39bca00-0cbf-11e9-906d-3646d0177472.png)

* **HTML of the section where the issue occurs**:

````html
<iframe src="https://community.home-assistant.io/embed/comments?embed_url=https%3A%2F%2Fwww.home-assistant.io%2Fblog%2F2018%2F12%2F27%2Fdata-science-portal%2F" id="discourse-embed-frame" width="100%" frameborder="0" scrolling="no" height="23745px"></iframe>
````

**Comment by Mottie** [comment]
I'm not sure what the best solution for this would be...

If I convert the `domain('community.home-assistant.io')` to `regexp("https://community.home-assistant.io(?!/embed)/.*")` then it will stop styling the embedded comments; but to fully implement this we'd need to change *all* the entries to use regexp.

**Comment by xt0rted** [comment]
@Mottie I realized that after I started looking through the stylesheet. I don't mind making the change but it feels kind of bloated since this is meant to run on many sites.

**Comment by Podesta** [comment]
I know [level1techs](https://level1techs.com) also use their discourse embedded for comments on the site. But personally, my solution there was different. Instead of removing the discourse embedded style, I made the site compliant with it.

**Comment by the-j0k3r** [comment]
I'll have a look at this convert to rexexp and exclude embeds

**Comment by xt0rted** [comment]
I don't use this style anymore so it doesn't matter to me if this change gets made or not.

**Comment by the-j0k3r** [comment]
This is pretty much a non issue now, maybe overdone the regex conversions in some domains but sod it, its done now.

Still cleanup in specific site area sis needed as followup.
