### ISSUE TITLE
More sites

### ISSUE THREAD

**Issue by JourneyOver** [StylishThemes/Discourse-Dark#2]
Two extra sites to add:

https://forums.sonarr.tv/
https://discuss.flexget.com/

**Comment by Mottie** [comment]
Hi @JourneyOver!

Thanks, updated!

**Comment by JourneyOver** [comment]
Just a note but for at least sonarr.tv there is a bit more that need to be done (as shown in the picture here https://i.imgur.com/3qGKFuC.png there are at least two examples), not just adding it to the list. I don't really know if there are more spots that needs to be fixed or not for sonarr.tv.

I believe flexgets forum is all good though as I didn't really notice anything right away.

Sorry I didn't mention this when I made this issue, was late and I totally forgot about it :x

**Comment by Mottie** [comment]
Fixed!

**Comment by JourneyOver** [comment]
Great :D will keep an eye out whenever I browse sonarrs/flexgets forums to see if I run into any other spots that end up needing fixed.
