### ISSUE TITLE
Add forum.sentry.io

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/Discourse-Dark#21]
https://forum.sentry.io/t/new-product-changes-now-available-for-preview/5805

Just adding the url to the list isn't enough, there's also some content that needs restyling but I'm not sure if this is universal to all sites or just this one.

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for finding this forum. I'm not sure if it's unique, but the background on that post is different because he's a moderator. So I think adding that selector should cover it. If not, we can always update 😸
