### ISSUE TITLE
Can't see titles in similar posts

### ISSUE THREAD

**Issue by Geobert** [StylishThemes/Discourse-Dark#22]
* **Browser**: Firefex
* **Operating System**: Win 10
* **Link to page with the issue**: new post page on https://users.rust-lang.org/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/72570/57972737-5a62f200-7996-11e9-9dea-66081bcdec98.png)

We can't see titles in the right part.
Without style:
![image](https://user-images.githubusercontent.com/72570/57972739-6d75c200-7996-11e9-975c-67fddc4515ec.png)

**Comment by Mottie** [comment]
Hi @Geobert!

Thanks for reporting this issue. It's been fixed!
