### ISSUE TITLE
Add discuss.huel.com & invert site-logos

### ISSUE THREAD

**Issue by grndkntrl** [StylishThemes/Discourse-Dark#24]
Hi,

This is for Huel's primary UK & Global forum at:

- https://discuss.huel.com/

I've added it manually to my copy in Stylus, but figured it would get overwritten the next time the userscript gets automatically updated.

The USA subsidiary has a [separate forum](https://discourse.huel.com/) which is already picked up by the `regexp("https?://discourse\\.\\S*")` entry).

The only cosmetic issue I've noticed so far is that the main "Huel" site-logo is usually black text on a white background, so I also added an entry to invert it for both the main UK/Global and the US sites (which are the exact same logo but have different paths/filenames on the Discourse CDN):

```
/* Huel UK & US site-logo colour inversion (black-on-white to white-on-black)*/
.title img[src*="db5d841204005adb07642c1c8eb76a1f96476f3d.png"]#site-logo,
.title img[src*="ec0be1b993a1ebbaf52a1719213c61a761150053.png"]#site-logo
{
	filter: invert(100%) !important;
}
```

Thanks!

**Comment by Mottie** [comment]
Hi @grndkntrl!

Thanks for letting us know, I'll have it added shortly.
