### ISSUE TITLE
Consistent installation urls

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/Discourse-Dark#25]
The link in the header of the repo is https://openusercss.org/theme/5b455a48562a680b00b749db while the instructions in the readme links to https://github.com/StylishThemes/Discourse-Dark/raw/master/discourse-dark.user.css. Should both of these be updated to point to https://raw.githubusercontent.com/StylishThemes/Discourse-Dark/master/discourse-dark.user.css like we do in the GitHub Dark repo?

**Comment by Mottie** [comment]
Hi @xt0rted!

When you add a userstyle to openusercss.org, it make a local copy in their database. I thought it was set up to update the userstyle from our GitHub repo, but I guess not. I'll have to look at the API when I get some time, but if it's too much effort, we'll just remove all our styles from there.

**Comment by the-j0k3r** [comment]
ping

**Comment by the-j0k3r** [comment]
See https://github.com/orgs/StylishThemes/teams/github/discussions/3/comments/4

**Comment by the-j0k3r** [comment]
again, ping @Mottie

**Comment by Mottie** [comment]
Sorry, what did you need me to do?

**Comment by the-j0k3r** [comment]
Fix the issue?

**Comment by xt0rted** [comment]
And only repo admins can update the url on the main page, if that's the route we're going which I think it is.

**Comment by Mottie** [comment]
There are only 4 styles hosted there... I updated the css & description with links to the associated repo, but it kept returning a database error. When I go into edit mode, the updates are there, but I don't see any changes from the main page of each style.

**Comment by Mottie** [comment]
There, I think deleting them sorta worked better... I still see the 4 styles, but an error pops up when you try to go to their page.

**Comment by the-j0k3r** [comment]
It seems fixed, when I visit openusercss I see

![Capture](https://user-images.githubusercontent.com/31389848/86524777-fd1e4e80-be7e-11ea-8a5d-e4a965c3f8a6.PNG)

**Comment by silverwind** [comment]
Openusercss is dead, I've updated the link on the repo page

https://openusercss.org/theme/5b455a48562a680b00b749db

to

https://github.com/StylishThemes/Discourse-Dark/raw/master/discourse-dark.user.css

**Comment by silverwind** [comment]
Oh, and I would not recommend to use GitHub's [custom emoji](https://github.com/ikatyang/emoji-cheat-sheet#github-custom-emoji) like :feelsgood: as they are removed per [this](https://github.com/github/gemoji/pull/158). Thought they still work I imagine they will eventually stop working on github.com. I've put another icon in place, if you have a better one, feel free to change.
