### ISSUE TITLE
Support https://discuss.rubyonrails.org/

### ISSUE THREAD

**Issue by juandazapata** [StylishThemes/Discourse-Dark#31]
**Describe the change you'd like**
https://discuss.rubyonrails.org/ looks like this
![image](https://user-images.githubusercontent.com/145506/80843619-c142e080-8bd2-11ea-9861-fbdddb818972.png)

**Additional context**

**Comment by the-j0k3r** [comment]
Thanks, styled as much as I saw logged off.
