### ISSUE TITLE
Add github.community

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/Discourse-Dark#34]
As of today the github community site is now using Discourse.

- **Link to the site**: https://github.community

**Comment by the-j0k3r** [comment]
Will need to do something to alert the GitHub Dark Community styles users somehow, I have an idea how to do it.

Gimme a while to get this done before updating here.

**Comment by the-j0k3r** [comment]
Lets hope the method I chose for the move will NOT crop up as an issue sooner or later =)

**Comment by xt0rted** [comment]
Just so everyone knows this theme isn't really needed, at least for github's instance. If you go under your account preferences there's 3 theme options which are GitHub, Light, and Dark.

`https://github.community/u/:username/preferences/interface`

![github community_u_xt0rted_preferences_interface](https://user-images.githubusercontent.com/831974/85230050-7b78ec00-b3bb-11ea-9933-a38647f55126.png)

**Comment by the-j0k3r** [comment]
Well that could be said about 99% of these.

**Comment by xt0rted** [comment]
I checked https://forum.sentry.io and that one doesn't have the theme option. Kind of sad that's not consistent across all of them.

**Comment by the-j0k3r** [comment]
I have also found those who became dark by default, due to stylesheets incompatibility, thus caused bugs  these obviously removed.
