### ISSUE TITLE
"color: #aaa !important;" doesn't work for ".user-stream .excerpt"

### ISSUE THREAD

**Issue by Kir-Antipov** [StylishThemes/Discourse-Dark#35]
* **Browser**: Firefox 78.0.1
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.community/u/kir-antipov
* **Screenshot**: 

![Bug](https://user-images.githubusercontent.com/40232067/86490726-11742580-bd71-11ea-8b97-bb472d6d11d7.png)

**Comment by the-j0k3r** [comment]
Thanks for the report.

Of course it does and doesnt require !important.

fix up in morning.

**Comment by the-j0k3r** [comment]
Also you can probably use https://github.com/StylishThemes/Feature-Override-Styles/blob/master/github-custom-border-radii.user.css

fix up in morning.
