### ISSUE TITLE
Add f-droid forums (forum.f-droid.org)

### ISSUE THREAD

**Issue by sameyepatch** [StylishThemes/Discourse-Dark#8]
As the title mentions, please add the F-droid forums. The theme works perfectly (except for the title next to the logo).

![](https://lambda.sx/gRI.png)

**Comment by Mottie** [comment]
Hi @sameyepatch!

Thanks for letting us know! The usercss has been updated in this repo. Please note that we are no longer updating userstyles.org, so to get this to work please install the style directly from our repo, or from https://openusercss.org/theme/5b455a48562a680b00b749db (except the main color customization isn't currently working on that site).
